export interface Guide {
  slug: string;
  title: string;
  subtitle: string;
  badge: string;
  what: string;
  whoNeeds: string;
  documents: string[];
  commonMistakes: string[];
  approvalTips: string[];
  officialLink: string;
}

export const guides: Guide[] = [
  {
    slug: "ds-160",
    title: "DS-160 Online Nonimmigrant Visa Application",
    subtitle: "The form every US nonimmigrant visa applicant must complete before their embassy interview.",
    badge: "US Visa",
    what: "The DS-160 is the US Department of State's Online Nonimmigrant Visa Application form. It collects biographic, travel, and background information from anyone applying for a nonimmigrant visa (tourist, student, work, exchange, etc.). You must submit it electronically at ceac.state.gov and bring the confirmation barcode to your interview.",
    whoNeeds: "Anyone applying for a US nonimmigrant visa including B-1/B-2 (tourist/business), F-1 (student), H-1B (work), J-1 (exchange visitor), L-1 (intracompany transfer), and most other nonimmigrant categories.",
    documents: [
      "Valid passport (at least 6 months validity beyond intended stay)",
      "Travel itinerary or proposed travel dates",
      "Recent passport-style photograph (2×2 inches, white background)",
      "US point of contact name and address",
      "Employer or school information",
      "Previous US visa (if any)",
      "Supporting documents for purpose of visit",
    ],
    commonMistakes: [
      "Entering name differently than on passport (include all given names)",
      "Wrong date format — DS-160 uses DD-MMM-YYYY (e.g. 15-JAN-1990)",
      "Leaving fields blank instead of entering 'Does Not Apply'",
      "Answering 'Yes' accidentally on security questions",
      "Submitting before checking all sections — you cannot edit after submission",
      "Using a photo with glasses or coloured background",
    ],
    approvalTips: [
      "Complete the form in one session or save the Application ID to return later",
      "Answer all security questions truthfully — inconsistencies cause denials",
      "List all social media handles including old accounts",
      "Use Formixa to prepare a correct reference document before typing into the official form",
      "Print the confirmation page with the barcode — you need it for your interview",
    ],
    officialLink: "https://ceac.state.gov/genniv/",
  },
  {
    slug: "f1-student-visa",
    title: "F-1 Student Visa",
    subtitle: "The primary visa for international students attending US colleges, universities, and language programs.",
    badge: "US Visa",
    what: "The F-1 visa is issued to full-time students enrolled in an academic or language program at a SEVP-approved US institution. It allows you to study in the US and work on-campus up to 20 hours/week. After completing your degree, you can apply for Optional Practical Training (OPT) to work in your field for 12–36 months.",
    whoNeeds: "International students admitted to a SEVP-approved US college, university, seminary, conservatory, academic high school, or language training program who need to maintain full-time enrollment.",
    documents: [
      "Form I-20 (Certificate of Eligibility) from your school's DSO",
      "DS-160 confirmation page with barcode",
      "SEVIS fee payment receipt (I-901)",
      "Valid passport (6+ months beyond intended stay)",
      "Visa application fee payment receipt (MRV fee)",
      "Acceptance letter from the US institution",
      "Financial proof: bank statements showing funds to cover 1 year of tuition + living expenses",
      "Academic transcripts and diplomas",
      "Standardized test scores (TOEFL, SAT, GRE, GMAT as applicable)",
      "Ties to home country: property ownership, family, job offer letter after graduation",
    ],
    commonMistakes: [
      "Insufficient financial proof — officers want to see 12 months of costs, not just tuition",
      "Weak ties to home country — must show intent to return after studies",
      "I-20 start date is past — make sure it is current",
      "SEVIS fee not paid at least 3 days before the interview",
      "Applying at wrong embassy — apply at the embassy in your country of residence",
      "Vague answers about study plans — know your program, career goals, and why this specific school",
    ],
    approvalTips: [
      "Prepare a clear, honest statement of purpose explaining why you chose the US and this school",
      "Bring evidence of strong home country ties (family, job offer, property)",
      "Know the key facts about your school and program",
      "Show financial documents for both yourself and your sponsor",
      "Practice common F-1 interview questions",
    ],
    officialLink: "https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html",
  },
  {
    slug: "b1-b2-tourist-visa",
    title: "B-1/B-2 Tourist & Business Visa",
    subtitle: "The most common US visitor visa for tourism, medical treatment, and short business trips.",
    badge: "US Visa",
    what: "The B-1/B-2 visa is a temporary nonimmigrant visa for people visiting the US for tourism, vacation, visiting family, medical treatment (B-2), or attending business meetings and conferences (B-1). It is typically issued for 10 years with multiple entries. CBP grants up to 6 months of stay per entry.",
    whoNeeds: "Anyone not from a Visa Waiver Program country who wants to visit the US for leisure, tourism, family visits, medical care, or short business activities. VWP country citizens can use ESTA instead for stays up to 90 days.",
    documents: [
      "Valid passport (6+ months beyond intended stay)",
      "DS-160 confirmation barcode",
      "Photo meeting US visa photo requirements",
      "Proof of sufficient funds (bank statements, pay slips)",
      "Proof of ties to home country (employment letter, property, family)",
      "Travel itinerary (flights, hotel bookings)",
      "Invitation letter (if visiting family or friends)",
      "Medical records (if visiting for treatment)",
      "Business meeting letter (for B-1 applicants)",
    ],
    commonMistakes: [
      "Weak demonstration of home country ties — most denials are under Section 214(b)",
      "Bringing too many ties to the US (property, close family) without offsetting ties home",
      "Vague itinerary — officers want to see a credible travel plan",
      "Overstay history — previous overstays severely impact approval chances",
      "Insufficient funds relative to planned trip length",
      "Not mentioning the correct purpose — B-1 and B-2 have different allowed activities",
    ],
    approvalTips: [
      "Show strong evidence of your intent to return: stable job, family, financial ties",
      "Have a clear, specific itinerary for your trip",
      "Be honest and concise at the interview — short, confident answers",
      "Bring organised documents in a folder — show you are prepared",
      "If previously denied, address the reason clearly",
    ],
    officialLink: "https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html",
  },
  {
    slug: "i-485-adjustment-of-status",
    title: "Form I-485 — Adjustment of Status",
    subtitle: "Apply for a green card (lawful permanent residence) while remaining in the United States.",
    badge: "Green Card",
    what: "Form I-485, Application to Register Permanent Residence or Adjust Status, is filed by eligible immigrants already in the US to apply for a green card without having to return to their home country for consular processing. It is typically filed together with I-864 (Affidavit of Support), I-765 (work permit), and I-131 (travel permit).",
    whoNeeds: "People in the US on a nonimmigrant visa (or other eligible status) who have an approved immigrant petition (I-130, I-140, etc.) and want to become lawful permanent residents without departing the US.",
    documents: [
      "Form I-485",
      "Approved I-130 or I-140 (or concurrent filing)",
      "Form I-864 Affidavit of Support from petitioner",
      "Valid passport",
      "Two passport-style photos",
      "Birth certificate with certified translation",
      "Form I-94 Arrival/Departure record",
      "Medical examination (Form I-693, sealed envelope from civil surgeon)",
      "Police clearance certificates from each country lived in for 6+ months",
      "Evidence of legal entry (visa stamp, I-94)",
      "Form G-1145 (e-notification, optional)",
    ],
    commonMistakes: [
      "Filing when there is no visa number available (priority date not current)",
      "Incorrect I-94 or evidence of unlawful presence",
      "Missing police clearance from all required countries",
      "I-693 medical exam expired (valid for 2 years from civil surgeon signature)",
      "Incorrect fee — USCIS fees change; verify on uscis.gov before sending",
      "Filing before I-130 is approved (unless concurrent filing is allowed)",
    ],
    approvalTips: [
      "Check the Visa Bulletin at travel.state.gov monthly to confirm your priority date is current",
      "Attend biometrics (ASC) and interview appointments — missing them causes denial",
      "Keep copies of everything you send to USCIS",
      "Respond to any RFE (Request for Evidence) promptly and completely",
      "Track your case at egov.uscis.gov using the receipt number",
    ],
    officialLink: "https://www.uscis.gov/i-485",
  },
  {
    slug: "i-130-petition",
    title: "Form I-130 — Petition for Alien Relative",
    subtitle: "Start the family-based green card process by filing a petition for your qualifying relative.",
    badge: "Green Card",
    what: "Form I-130, Petition for Alien Relative, is filed by a US citizen or lawful permanent resident to establish a qualifying relationship with a foreign national relative. Approval of the I-130 does not grant any immigration benefit on its own — it simply sets a priority date and places the relative in a visa queue. The relative must then go through consular processing or I-485.",
    whoNeeds: "US citizens who want to sponsor a spouse, child (under 21), parent, adult son/daughter, or sibling. Lawful permanent residents can sponsor a spouse or unmarried child.",
    documents: [
      "Form I-130 and Form I-130A (for spousal petitions)",
      "Proof of your US citizenship or LPR status",
      "Proof of qualifying relationship: marriage certificate, birth certificate",
      "Petitioner's government-issued photo ID",
      "Evidence of bona fide relationship (for spouses): photos, communication, joint finances",
      "Filing fee (verify current amount at uscis.gov)",
    ],
    commonMistakes: [
      "Missing proof of the qualifying relationship",
      "Insufficient evidence of a bona fide marriage (for spousal petitions)",
      "Not including certified translations of non-English documents",
      "Wrong fee or outdated form version",
      "Filing without understanding the visa bulletin wait times for your category",
    ],
    approvalTips: [
      "File as soon as possible — the priority date is set on the filing date, not approval",
      "Organise relationship evidence chronologically",
      "Immediately notify USCIS of any address changes using Form AR-11",
      "For marriage petitions, include a variety of evidence: photos, messages, financial records, travel together",
    ],
    officialLink: "https://www.uscis.gov/i-130",
  },
  {
    slug: "i-765-employment-authorization",
    title: "Form I-765 — Employment Authorization Document (EAD)",
    subtitle: "Apply for the right to work legally in the United States.",
    badge: "Work Permit",
    what: "Form I-765, Application for Employment Authorization, is filed to request an Employment Authorization Document (EAD card) that allows you to work legally in the US. It is used by adjustment of status applicants, asylum seekers, DACA recipients, F-1 students applying for OPT, and various other categories.",
    whoNeeds: "Pending green card applicants (I-485 filed), F-1 students applying for OPT/STEM OPT, asylum applicants, TPS holders, DACA recipients, J-2 dependents, and certain other nonimmigrant categories that allow work authorization.",
    documents: [
      "Form I-765",
      "Two passport-style photos",
      "Copy of I-94 Arrival/Departure record",
      "Copy of passport biographical page",
      "Evidence of eligible immigration status or category",
      "Filing fee (waived for certain categories; verify at uscis.gov)",
      "For OPT: I-20 with DSO OPT recommendation",
    ],
    commonMistakes: [
      "Filing under the wrong eligibility category — check your specific situation carefully",
      "Submitting without required supporting documents for your category",
      "Working before the EAD card arrives — unauthorized employment is a serious violation",
      "Not filing a renewal early enough — file 6 months before expiration",
      "Missing the OPT application window (must file within 30 days of DSO recommendation)",
    ],
    approvalTips: [
      "File early — processing can take 3–6 months",
      "Apply for a renewal 6 months before expiration to avoid gaps",
      "If filed with I-485, combo card also serves as advance parole for travel",
      "Keep copies of your EAD front and back and your filing receipt",
    ],
    officialLink: "https://www.uscis.gov/i-765",
  },
  {
    slug: "uk-visit-visa",
    title: "UK Standard Visitor Visa",
    subtitle: "Visit the United Kingdom for tourism, business, or family visits for up to 6 months.",
    badge: "UK Visa",
    what: "The UK Standard Visitor Visa allows you to visit the UK for up to 6 months for tourism, visiting friends and family, attending business meetings, conferences, or short courses. Applications are submitted online and biometrics are given at a Visa Application Centre. The visa can be valid for 6 months, 2 years, 5 years, or 10 years.",
    whoNeeds: "Nationals of countries that require a visa to enter the UK, who wish to visit for leisure, tourism, family visits, business activities, medical treatment, or short-term study (up to 30 days).",
    documents: [
      "Valid passport (must be valid for the duration of your visit)",
      "Completed online UK visa application form",
      "Biometric information (given at Visa Application Centre)",
      "Bank statements for the last 6 months",
      "Proof of accommodation (hotel bookings or invitation letter)",
      "Travel itinerary (flights, places to visit)",
      "Proof of employment: employment letter, payslips",
      "Proof of financial means to cover the trip",
      "Ties to home country (property, job, family)",
      "Previous UK or Schengen visas (strengthen application)",
    ],
    commonMistakes: [
      "Insufficient financial evidence — must show funds for the entire trip",
      "Incomplete travel itinerary",
      "Not explaining the purpose of visit clearly in the online form",
      "Submitting inconsistent information across documents",
      "Not providing evidence of ties to home country",
      "Applying for the wrong visa category",
    ],
    approvalTips: [
      "Apply at least 3 months before travel during peak season",
      "Include a cover letter explaining your trip purpose, itinerary, and ties to home country",
      "Use the UKVI priority service for faster processing",
      "Having a history of travel to the UK, US, or Schengen area significantly helps",
      "Use the GOV.UK official application portal at gov.uk/standard-visitor-visa",
    ],
    officialLink: "https://www.gov.uk/standard-visitor",
  },
  {
    slug: "canada-pr-express-entry",
    title: "Canada Permanent Residence — Express Entry",
    subtitle: "The fastest pathway to Canadian permanent residence for skilled workers.",
    badge: "Canada PR",
    what: "Express Entry is Canada's points-based immigration management system for three federal economic immigration programs: the Federal Skilled Worker Program, the Federal Skilled Trades Program, and the Canadian Experience Class. Candidates are ranked using the Comprehensive Ranking System (CRS) score. IRCC issues Invitations to Apply (ITA) to the highest-scoring candidates in regular draws.",
    whoNeeds: "Skilled workers with foreign work experience (FSWP), people with Canadian work experience (CEC), skilled tradespeople (FSTP), and those with a provincial nomination (+600 CRS points). A high CRS score (typically 470–550+) is needed to receive an ITA in a general draw.",
    documents: [
      "Valid passport",
      "Educational Credential Assessment (ECA) from a IRCC-approved body",
      "Language test results: IELTS or CELPIP (English), TEF or TCF (French)",
      "Work experience proof: reference letters, pay stubs, T4s, employment contracts",
      "Provincial Nomination Certificate (if applicable)",
      "Police clearance certificates from all countries lived in",
      "Medical examination from a panel physician",
      "Proof of funds (unless you have a valid Canadian job offer)",
      "Birth certificates for all family members being included",
    ],
    commonMistakes: [
      "Inaccurate job NOC code — match your duties carefully to the correct NOC",
      "Insufficient proof of work experience — need detailed reference letters",
      "Language test scores below minimum requirements",
      "Not creating an Express Entry profile early enough",
      "Using an expired ECA or language test (both have validity periods)",
      "Not keeping profile updated with new credentials or job changes",
    ],
    approvalTips: [
      "Maximise your CRS score by improving language scores, completing a second language test, or getting a provincial nomination",
      "Consider the Provincial Nominee Program (PNP) for a path with lower CRS requirements",
      "Get a job offer from a Canadian employer — adds 50–200 CRS points",
      "French language skills open category-based draws with lower CRS cutoffs",
      "Use IRCC's CRS calculator at ircc.canada.ca to track your score",
    ],
    officialLink: "https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html",
  },
  {
    slug: "h1b-work-visa",
    title: "H-1B Specialty Occupation Work Visa",
    subtitle: "The most common US work visa for professionals in specialty occupations sponsored by a US employer.",
    badge: "US Visa",
    what: "The H-1B is a nonimmigrant work visa for foreign nationals employed in specialty occupations that require at least a bachelor's degree or equivalent in a specific field. Employers file the petition on behalf of the worker. H-1B is subject to an annual cap of 65,000 visas (plus 20,000 for US master's degree holders) with selection by lottery. Cap-exempt employers include universities, nonprofits, and government research organisations.",
    whoNeeds: "Foreign nationals with a US employer sponsor who has a specialty occupation job offer requiring at least a bachelor's degree. Common fields include IT, engineering, finance, architecture, medicine, and academia. Cap-exempt workers include those employed at universities or research institutions.",
    documents: [
      "Form I-129 (Petition for Nonimmigrant Worker) — filed by employer",
      "Labor Condition Application (LCA) certified by Department of Labor",
      "Employer support letter detailing job duties and qualifications required",
      "Employee's degree certificates and transcripts",
      "Credential evaluation (if degree is from outside the US)",
      "Resume/CV showing relevant work experience",
      "Copy of passport biographical page",
      "Previous visa and I-94 (if already in the US)",
      "DS-160 and visa application fee (for consular processing)",
    ],
    commonMistakes: [
      "Missing the H-1B lottery registration window (March each year)",
      "LCA wage level too low — must meet or exceed prevailing wage for the role and location",
      "Job duties don't qualify as a specialty occupation — must require a specific degree",
      "Degree field doesn't directly relate to the job offered",
      "Employer not registered for E-Verify (required for H-1B sponsors)",
      "Not filing premium processing when starting date is critical",
    ],
    approvalTips: [
      "Register in the lottery in March — selection is random so register as early as possible",
      "Use premium processing ($2,805 fee) for a 15-business-day decision guarantee",
      "Ensure the job description clearly maps to a specialty occupation with degree requirement",
      "STEM and IT roles have the highest approval rates — frame duties specifically",
      "Cap-exempt employers (universities, nonprofits) can file any time without the lottery",
    ],
    officialLink: "https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations",
  },
  {
    slug: "h4-dependent-visa",
    title: "H-4 Dependent Visa",
    subtitle: "For spouses and unmarried children under 21 of H-1B visa holders.",
    badge: "US Visa",
    what: "The H-4 visa allows spouses and unmarried children under 21 of H-1B workers to live in the United States. H-4 holders may study and attend school. H-4 spouses whose H-1B spouse has an approved I-140 immigrant petition may apply for an H-4 EAD (Employment Authorization Document), allowing them to work in any job without restriction.",
    whoNeeds: "Spouses and unmarried children (under 21) of valid H-1B visa holders. Children born in the US are US citizens and do not need H-4 status. The principal H-1B holder must maintain valid status for the H-4 holder to remain in status.",
    documents: [
      "Form I-539 (Application to Extend/Change Nonimmigrant Status) — if already in the US",
      "DS-160 and visa application fee (for consular processing abroad)",
      "Principal H-1B holder's valid visa, I-94, and I-797 approval notice",
      "Marriage certificate (for spouse) or birth certificate (for children)",
      "Certified translations of all non-English documents",
      "Passport valid for at least 6 months beyond stay",
      "Two passport photos",
      "Form I-765 + I-140 approval notice (if applying for H-4 EAD)",
    ],
    commonMistakes: [
      "Applying for H-4 EAD without a principal spouse who has an approved I-140",
      "Overstaying H-4 status when H-1B spouse changes or loses their status",
      "Children aging out — H-4 status ends at 21; timely planning is required",
      "Not updating H-4 status when H-1B is extended or changed",
      "Missing the I-539 filing deadline — must file before H-4 status expires",
    ],
    approvalTips: [
      "File the H-4 concurrently with the H-1B petition to save time",
      "If the H-1B spouse has an approved I-140, apply for H-4 EAD immediately — it allows unrestricted work",
      "Keep copies of the H-1B principal's I-797 and I-94 at all times",
      "Track expiry dates carefully — H-4 status is tied to H-1B validity",
    ],
    officialLink: "https://www.uscis.gov/humanitarian/abused-spouses-children-and-parents/h-4-nonimmigrant-status",
  },
  {
    slug: "o1-extraordinary-ability",
    title: "O-1 Extraordinary Ability Visa",
    subtitle: "For individuals with extraordinary ability or achievement in their field.",
    badge: "US Visa",
    what: "The O-1 visa is for individuals with extraordinary ability in sciences, arts, education, business, or athletics (O-1A), or extraordinary achievement in the motion picture or TV industry (O-1B). 'Extraordinary ability' means sustained national or international acclaim demonstrated by receipt of a major award or meeting at least 3 of 8 regulatory criteria.",
    whoNeeds: "Top-tier professionals, athletes, scientists, artists, researchers, entrepreneurs, and entertainers who can demonstrate sustained national or international recognition in their field. Unlike H-1B, there is no annual cap and no lottery.",
    documents: [
      "Form I-129 filed by a US employer, agent, or organisation",
      "Consultation letter from a peer group, labour organisation, or expert in the field",
      "Evidence of extraordinary ability: major award (Oscar, Nobel, Olympic medal, etc.) OR at least 3 of: high salary, critical role in distinguished organisations, media coverage, judging others' work, original contributions, scholarly articles, leading role",
      "Contracts, itineraries, or letters of intent for planned US activities",
      "Detailed written opinion letter from an immigration attorney (strongly recommended)",
      "Passport valid for at least 6 months beyond stay",
    ],
    commonMistakes: [
      "Insufficient evidence — quality matters more than quantity; weak evidence causes RFEs",
      "Missing the peer consultation requirement — required for all O-1 petitions",
      "Confusing O-1A (general) and O-1B (arts/entertainment) criteria",
      "No clear itinerary or contract for US activities",
      "Relying solely on social media following without tangible industry recognition",
      "Filing without an immigration attorney — O-1 petitions are complex",
    ],
    approvalTips: [
      "Compile a comprehensive evidence portfolio: press coverage, awards, salary comparisons, reference letters from industry leaders",
      "Premium processing is available and recommended — O-1 RFEs are common without a strong initial filing",
      "Entrepreneurs can qualify under O-1A if they demonstrate extraordinary achievement in business",
      "Unlike H-1B, you can file O-1 at any time of year with no lottery",
      "An immigration attorney's involvement significantly improves outcomes",
    ],
    officialLink: "https://www.uscis.gov/working-in-the-united-states/temporary-workers/o-1-visa-individuals-with-extraordinary-ability-or-achievement",
  },
  {
    slug: "l1-intracompany-transfer",
    title: "L-1 Intracompany Transferee Visa",
    subtitle: "Transfer to a US office of your multinational employer as a manager, executive, or specialised knowledge worker.",
    badge: "US Visa",
    what: "The L-1 visa allows multinational companies to transfer employees from foreign offices to US offices. L-1A is for managers and executives (allows EB-1C green card path). L-1B is for workers with specialised knowledge. The employee must have worked for the company abroad for at least 1 continuous year within the last 3 years.",
    whoNeeds: "Employees of multinational companies who have worked for the same employer (or affiliate/subsidiary) outside the US for at least 1 year in the past 3 years in a managerial, executive, or specialised knowledge capacity.",
    documents: [
      "Form I-129 with L supplement filed by the US employer",
      "Evidence of qualifying relationship between US and foreign entity (ownership, control documents)",
      "Evidence of the employee's 1 year of qualifying employment abroad (letters, pay stubs, org charts)",
      "Job description for the US position clearly showing managerial/executive or specialised knowledge duties",
      "Employee's resume and educational credentials",
      "Passport valid for at least 6 months beyond stay",
      "DS-160 and visa application fee (for consular processing)",
    ],
    commonMistakes: [
      "Insufficient evidence of qualifying relationship between foreign and US entities",
      "L-1B specialised knowledge claim too vague — must describe proprietary knowledge specifically",
      "Managerial role that is mostly hands-on work — USCIS scrutinises 'function managers' closely",
      "Employee did not work full-time for 1 continuous year abroad",
      "New office L-1 (for newly established US offices) requires a detailed business plan",
    ],
    approvalTips: [
      "L-1A (manager/executive) is a direct path to an EB-1C green card — plan strategically",
      "Large companies can use a Blanket L petition to transfer employees faster without individual I-129s",
      "Document the managerial role with org charts showing direct reports",
      "Use premium processing for time-sensitive transfers",
      "New office petitions are approved for 1 year only — plan the extension with strong revenue evidence",
    ],
    officialLink: "https://www.uscis.gov/working-in-the-united-states/temporary-workers/l-1a-intracompany-transferee-executive-or-manager",
  },
  {
    slug: "j1-exchange-visitor",
    title: "J-1 Exchange Visitor Visa",
    subtitle: "For participants in approved exchange programs including students, researchers, au pairs, and interns.",
    badge: "US Visa",
    what: "The J-1 Exchange Visitor Program is administered by the US Department of State and covers dozens of program categories: au pair, camp counsellor, college student, intern, physician, professor, researcher, secondary school student, summer work travel, teacher, and trainee. The J-1 sponsor organisation issues the DS-2019 form which initiates the visa process. Many J-1 holders are subject to the 2-year home country physical presence requirement.",
    whoNeeds: "Individuals participating in a US government-designated exchange program through a sponsoring organisation. Each programme category has its own eligibility rules — participants must be sponsored by a J-1 sponsor organisation and receive a DS-2019 certificate of eligibility.",
    documents: [
      "DS-2019 Certificate of Eligibility issued by the J-1 sponsor organisation",
      "DS-160 visa application form",
      "SEVIS fee payment receipt (Form I-901, $220 or $35 for government-funded programs)",
      "Valid passport (6+ months beyond stay)",
      "Financial evidence showing ability to support yourself during the program",
      "Proof of ties to home country",
      "Programme offer letter or acceptance documentation",
      "Health insurance meeting J-1 minimum requirements",
    ],
    commonMistakes: [
      "Not checking whether you are subject to the 2-year home residency requirement (§212(e)) — this bars H, L, and immigrant visa applications without a waiver",
      "Choosing an unauthorised programme activity — J-1 activities are restricted to what the DS-2019 specifies",
      "Travelling outside the US without checking re-entry rules",
      "Inadequate health insurance — J-1 regulations set specific minimum coverage amounts",
      "Missing the SEVIS fee payment before the visa interview",
    ],
    approvalTips: [
      "Check early if your country or funding source triggers the 2-year home residency rule",
      "If subject to §212(e), begin the waiver process (IGA waiver, No Objection, etc.) early if you plan to stay in the US",
      "Maintain contact with your sponsor's Responsible Officer (RO) throughout the programme",
      "Health insurance must meet exact J-1 minimums — verify your policy before arrival",
    ],
    officialLink: "https://travel.state.gov/content/travel/en/us-visas/study/exchange.html",
  },
  {
    slug: "k1-fiance-visa",
    title: "K-1 Fiancé(e) Visa",
    subtitle: "Bring your foreign fiancé(e) to the United States to get married within 90 days.",
    badge: "US Visa",
    what: "The K-1 visa allows the foreign-citizen fiancé(e) of a US citizen to enter the United States for 90 days to get married. After marriage, the K-1 holder must file Form I-485 to adjust status to lawful permanent resident. The couple must have met in person within 2 years before filing (unless extreme hardship or cultural custom exceptions apply).",
    whoNeeds: "US citizens who intend to marry a foreign national within 90 days of the fiancé(e)'s arrival in the US. Both parties must be legally free to marry and must have met in person within the past 2 years.",
    documents: [
      "Form I-129F (Petition for Alien Fiancé(e)) filed by the US citizen",
      "Proof of US citizenship (passport, birth certificate, naturalisation certificate)",
      "Proof of termination of any prior marriages (divorce decrees, death certificates)",
      "Evidence of bona fide relationship: photos together, communications, travel records",
      "Evidence of in-person meeting within 2 years",
      "Fiancé(e)'s valid passport and birth certificate",
      "Police clearance certificates from all countries lived in (for fiancé(e))",
      "Medical examination by approved panel physician (done at the embassy)",
      "Affidavit of Support (Form I-134) from US citizen petitioner",
    ],
    commonMistakes: [
      "Couple has not met in person within 2 years before filing — a waiver is required but rarely granted",
      "Insufficient relationship evidence — USCIS scrutinises K-1 petitions for fraud",
      "Not getting married within 90 days — K-1 status cannot be extended; overstay has serious consequences",
      "US petitioner's income below 100% of federal poverty guideline",
      "Not filing I-485 promptly after marriage — K-1 status does not confer work authorization until EAD is issued",
    ],
    approvalTips: [
      "Start collecting evidence of the relationship early: dated photos, travel records, messages, video call logs",
      "File I-485 + I-765 (EAD) + I-131 (travel permit) simultaneously right after marriage",
      "The US petitioner should write a detailed personal statement about the relationship history",
      "Attend the embassy interview together if the country allows it",
      "After green card approval, the couple will have a 2-year conditional green card — file I-751 together before it expires",
    ],
    officialLink: "https://www.uscis.gov/family/family-of-us-citizens/k-1-nonimmigrant-visa-for-a-fianc%C3%A9e",
  },
  {
    slug: "tn-visa",
    title: "TN Visa — USMCA Professional Work Visa",
    subtitle: "Streamlined work authorisation for Canadian and Mexican professionals under the USMCA trade agreement.",
    badge: "US Visa",
    what: "The TN visa is a nonimmigrant work visa available exclusively to Canadian and Mexican citizens under the United States-Mexico-Canada Agreement (USMCA, formerly NAFTA). It covers over 60 specific professional categories including accountants, engineers, lawyers, scientists, nurses, and computer systems analysts. Canadians apply at the US border; Mexicans apply at a US consulate.",
    whoNeeds: "Canadian and Mexican citizens who have a job offer in one of the designated TN professional categories and hold the required educational qualifications for that category. The employer must be a US company.",
    documents: [
      "Valid Canadian or Mexican passport",
      "Employer support letter describing: job title, duties, qualifications required, length of employment, and salary",
      "Proof of qualifications for the specific TN category (degree, professional licence, membership)",
      "Form DS-160 + visa application fee (Mexican citizens, consular processing only)",
      "Proof of Canadian or Mexican citizenship",
      "Evidence that the position falls within an approved TN occupation list",
    ],
    commonMistakes: [
      "Job title or duties don't match a qualifying TN occupation precisely",
      "Degree is in an unrelated field — the degree must match the TN category",
      "Employer letter is vague or missing required details",
      "Canadians trying to enter for a profession that is not on the TN list",
      "Showing immigrant intent — TN requires non-immigrant intent, though concurrent green card filing is allowed under certain conditions",
    ],
    approvalTips: [
      "Canadians: apply at any US port of entry — approval is typically same-day with no appointment needed",
      "Mexicans: apply at the US consulate in Mexico with the full application package",
      "The employer letter is the most critical document — have a lawyer review it",
      "TN is granted for up to 3 years and can be renewed indefinitely",
      "Keep a copy of your TN approval (I-94) and employer letter at all times",
    ],
    officialLink: "https://www.uscis.gov/working-in-the-united-states/temporary-workers/tn-nafta-professionals",
  },
  {
    slug: "e2-investor-visa",
    title: "E-2 Treaty Investor Visa",
    subtitle: "Invest in and operate a US business if your country has a commerce treaty with the United States.",
    badge: "US Visa",
    what: "The E-2 Treaty Investor visa allows nationals of countries that maintain a commerce and navigation treaty with the United States to enter and work in the US based on a substantial investment in a US business. The investor must own at least 50% of the enterprise or have operational control. E-2 is renewable indefinitely in 2–5 year increments as long as the business is active.",
    whoNeeds: "Nationals of E-2 treaty countries who have invested or are actively investing a substantial amount of capital in a bona fide US enterprise and are directing and developing that enterprise. Common nationalities include UK, Germany, Japan, South Korea, Italy, and many others. Indian and Chinese nationals cannot currently obtain E-2 (no treaty).",
    documents: [
      "DS-160 visa application form",
      "Evidence of treaty country nationality (passport)",
      "Evidence of investment: bank wire transfers, invoices, contracts, lease agreements, purchase documents",
      "Business plan with financial projections (5 years)",
      "Evidence the investment is 'at risk': active business operations, inventory, equipment",
      "Proof of ownership: articles of incorporation, operating agreement",
      "Evidence the investment is substantial relative to the total cost of the business",
      "Evidence the business is more than 'marginal' — must support more than just the investor and family",
    ],
    commonMistakes: [
      "Investment amount too low — 'substantial' is judged proportionally; a $50K franchise may qualify, a $50K restaurant may not",
      "Funds not 'at risk' — money in a bank account without being actively committed to the business doesn't qualify",
      "Business is 'marginal' — it must have the capacity to generate income beyond supporting just the owner",
      "Investor does not own at least 50% of the enterprise",
      "Applying from a non-treaty country — check the treaty country list before applying",
    ],
    approvalTips: [
      "Franchises are popular E-2 investments — the established model helps demonstrate non-marginality",
      "A detailed, professionally prepared business plan significantly strengthens the application",
      "Document every dollar invested with paper trails (wire transfers, receipts)",
      "E-2 spouses automatically receive E-2 dependent status and can apply for an EAD to work",
      "Consult an immigration attorney familiar with E-2 — the substantiality test is nuanced",
    ],
    officialLink: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/all-visa-categories.html",
  },
  {
    slug: "opt-stem-opt",
    title: "OPT and STEM OPT for F-1 Students",
    subtitle: "Work in the US in your field of study for 12 to 36 months after graduating on an F-1 visa.",
    badge: "US Visa",
    what: "Optional Practical Training (OPT) allows F-1 students to work in the US in a job directly related to their major field of study. Standard OPT is 12 months and is available pre-completion or post-completion of a degree. STEM OPT is a 24-month extension available to students who graduate with a qualifying STEM degree and work for an E-Verify employer, giving up to 36 months of total OPT.",
    whoNeeds: "F-1 students who have been enrolled full-time for at least one academic year and want to gain work experience related to their degree. STEM OPT extension requires a degree in a qualifying STEM field (the DHS STEM list) and an employer enrolled in E-Verify.",
    documents: [
      "Form I-765 (Application for Employment Authorization)",
      "I-20 with DSO OPT recommendation dated within 30 days",
      "Copy of passport, visa, and I-94",
      "Two passport-style photos",
      "SEVIS fee payment receipt (for initial OPT only)",
      "For STEM OPT extension: Form I-983 (Training Plan) signed by employer, evidence of qualifying STEM degree, E-Verify company ID",
    ],
    commonMistakes: [
      "Missing the OPT application window: must apply no earlier than 90 days before graduation and no later than 60 days after",
      "Working before the EAD card arrives — even 1 day early is unauthorized employment",
      "Working in a job not related to the degree field",
      "STEM OPT employers not enrolled in E-Verify — disqualifies the extension",
      "Not filing STEM OPT extension before OPT EAD expires — 180-day automatic extension only applies if filed on time",
      "Exceeding the 90-day unemployment limit during OPT period",
    ],
    approvalTips: [
      "Apply as early as allowed (90 days before graduation) — USCIS takes 3–5 months",
      "Track your 90-day unemployment limit carefully — exceeding it violates F-1 status",
      "For STEM OPT, submit Form I-983 with the employer before filing I-765",
      "Students can do up to 12 months of pre-completion OPT, but it reduces post-completion OPT",
      "Start the H-1B lottery process during OPT — cap-gap provision bridges OPT to H-1B if selected",
    ],
    officialLink: "https://www.uscis.gov/opt",
  },
  {
    slug: "daca-renewal",
    title: "DACA Renewal Guide",
    subtitle: "How to renew Deferred Action for Childhood Arrivals (DACA) and maintain work authorisation.",
    badge: "US Visa",
    what: "DACA (Deferred Action for Childhood Arrivals) is a federal policy that protects certain undocumented individuals who came to the US as children from deportation and provides them with a 2-year renewable work permit (EAD). DACA does not provide a path to permanent residence or citizenship but does grant 'lawful presence' for the duration of the grant. As of 2024, DACA is subject to ongoing litigation — recipients should monitor legal developments closely.",
    whoNeeds: "Current DACA recipients whose DACA and EAD are approaching expiration. Initial DACA applications are not currently being accepted for new applicants (only renewals). Recipients must continue to meet eligibility criteria: continuous US residence since June 15, 2007, age under 31 on June 15, 2012, no disqualifying criminal history.",
    documents: [
      "Form I-821D (Consideration of Deferred Action for Childhood Arrivals)",
      "Form I-765 (Application for Employment Authorization)",
      "Form I-765WS (Worksheet)",
      "Filing fees: $495 (I-821D is free, I-765 is $495)",
      "Copy of current EAD (front and back)",
      "Two passport-style photos",
      "Copy of any government-issued ID",
      "Evidence of continuous US residence (if requested)",
    ],
    commonMistakes: [
      "Filing too late — USCIS recommends filing 150–180 days (5–6 months) before expiration",
      "Felony or significant misdemeanour convictions since last grant can disqualify renewal",
      "Travelling outside the US without advance parole — causes automatic termination of DACA",
      "Submitting incorrect filing fee or outdated form version",
      "Not keeping copies of all submitted documents",
    ],
    approvalTips: [
      "File 5–6 months before your current DACA and EAD expire — processing takes 4–6 months",
      "Monitor USCIS case status online and respond to any RFE within the deadline",
      "Do not travel internationally without approved advance parole — it terminates DACA",
      "Keep your address updated with USCIS using Form AR-11",
      "Monitor litigation updates from organisations like NILC, ACLU, and USCIS.gov — policy can change",
      "Consult a nonprofit immigration legal services provider for free or low-cost assistance",
    ],
    officialLink: "https://www.uscis.gov/DACA",
  },
];

export function getGuide(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}
